name: Generate File List

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run PowerShell Command
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -File | Select-Object FullName > file_list.txt

    - name: Commit and Push File List
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add file_list.txt
        git commit -m "Update file_list.txt [skip ci]" || exit 0
        git push
